// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Context;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230406195951_Prompt1_2")]
    partial class Prompt1_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("backend.Models.AccessTokens", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("accessTokens");
                });

            modelBuilder.Entity("backend.Models.Prompt1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("DD_a_l")
                        .HasColumnType("int")
                        .HasColumnName("DD.a.l");

                    b.Property<int>("DD_e_five")
                        .HasColumnType("int")
                        .HasColumnName("DD.e.five");

                    b.Property<int>("DD_five_r")
                        .HasColumnType("int")
                        .HasColumnName("DD.five.r");

                    b.Property<int>("DD_i_e")
                        .HasColumnType("int")
                        .HasColumnName("DD.i.e");

                    b.Property<int>("DD_n_a")
                        .HasColumnType("int")
                        .HasColumnName("DD.n.a");

                    b.Property<int>("DD_o_n")
                        .HasColumnType("int")
                        .HasColumnName("DD.o.n");

                    b.Property<int>("DD_period_t")
                        .HasColumnType("int")
                        .HasColumnName("DD.period.t");

                    b.Property<int>("DD_r_o")
                        .HasColumnType("int")
                        .HasColumnName("DD.r.o");

                    b.Property<int>("DD_t_i")
                        .HasColumnType("int")
                        .HasColumnName("DD.t.i");

                    b.Property<int>("DU_a_l")
                        .HasColumnType("int")
                        .HasColumnName("DU.a.l");

                    b.Property<int>("DU_e_five")
                        .HasColumnType("int")
                        .HasColumnName("DU.e.five");

                    b.Property<int>("DU_five_r")
                        .HasColumnType("int")
                        .HasColumnName("DU.five.r");

                    b.Property<int>("DU_i_e")
                        .HasColumnType("int")
                        .HasColumnName("DU.i.e");

                    b.Property<int>("DU_n_a")
                        .HasColumnType("int")
                        .HasColumnName("DU.n.a");

                    b.Property<int>("DU_o_n")
                        .HasColumnType("int")
                        .HasColumnName("DU.o.n");

                    b.Property<int>("DU_period_t")
                        .HasColumnType("int")
                        .HasColumnName("DU.period.t");

                    b.Property<int>("DU_r_o")
                        .HasColumnType("int")
                        .HasColumnName("DU.r.o");

                    b.Property<int>("DU_t_i")
                        .HasColumnType("int")
                        .HasColumnName("DU.t.i");

                    b.Property<int>("H_a")
                        .HasColumnType("int")
                        .HasColumnName("H.a");

                    b.Property<int>("H_e")
                        .HasColumnType("int")
                        .HasColumnName("H.e");

                    b.Property<int>("H_five")
                        .HasColumnType("int")
                        .HasColumnName("H.five");

                    b.Property<int>("H_i")
                        .HasColumnType("int")
                        .HasColumnName("H.i");

                    b.Property<int>("H_l")
                        .HasColumnType("int")
                        .HasColumnName("H.l");

                    b.Property<int>("H_n")
                        .HasColumnType("int")
                        .HasColumnName("H.n");

                    b.Property<int>("H_o")
                        .HasColumnType("int")
                        .HasColumnName("H.o");

                    b.Property<int>("H_period")
                        .HasColumnType("int")
                        .HasColumnName("H.period");

                    b.Property<int>("H_r")
                        .HasColumnType("int")
                        .HasColumnName("H.r");

                    b.Property<int>("H_t")
                        .HasColumnType("int")
                        .HasColumnName("H.t");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("Prompt1");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.testModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("testModel");
                });

            modelBuilder.Entity("backend.Models.AccessTokens", b =>
                {
                    b.HasOne("backend.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("backend.Models.Prompt1", b =>
                {
                    b.HasOne("backend.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
